Repository sinonjs/sinon, pull requests merged in 2019-12, with the labels that each got.

#2148 Remove old apis
  lib/sinon.js
  test/sinon-test.js
Labels: semver:major

#2175 Upgrade nise and browserify
  build.js
  lib/sinon/assert.js
  lib/sinon/util/core/next-tick.js
  lib/sinon/util/fake-timers.js
  package-lock.json
  package.json
  test/fake-test.js
  test/issues/issues-test.js
  test/mock-test.js
  test/proxy-call-test.js
  test/sandbox-test.js
  test/spy-test.js
  test/stub-test.js
  test/util/fake-timers-test.js
Labels: semver:major

#2179 Upgrade nise, @sinonjs/formatiom, @sinonjs/samsam and @sinonjs/referee
  package-lock.json
  package.json
  test/fake-test.js
  test/proxy-call-test.js
  test/sandbox-test.js
  test/spy-test.js
Labels: semver:major

#2181 Force upgrade @sinonjs/commons
  package.json
Labels: semver:patch

#2185 Upgrade nise to 3.0.1
  package-lock.json
  package.json
Labels: semver:patch

#2055 Document fake timer *Async() methods
  docs/release-source/release/fake-timers.md
Labels: pinned
